# Main Jekyll Configuration file.
#
# Jekyll needs to be restarted if you make any changes.
# For more information see the documentation.

# Basic site settings.
locale: "nl_NL"
timezone: Europe/Amsterdam
domain: "ieni.org"

# Page content variables.
title: "Vakvereniging i&amp;i"
short: "i&amp;i"
description: "Vakvereniging i&amp;i maakt zich sterk voor een structureel aanbod van kwalitatief
hoogwaardig onderwijs ten behoeve van informatica en digitale geletterdheid op alle basis- en
middelbare scholen in Nederland. Iedereen die zich vanuit welke functie dan ook betrokken voelt
bij informatica en digitale geletterdheid in het onderwijs verwelkomen wij graag als lid."
legal: "Vereniging voor Informatiekunde en Informatietechnologie in Onderwijs"
kvk: "KvK 40481134 te Utrecht"

# API credentials / Site Keys.
# Keys are whitelisted for this specific domain and intended for front-end
# usage. They can thus be safely committed to this public repository.
credentials:
  postcode: "fa930f80-b571-4796-8246-6fb93c5d23df"

# Jekyll collections for pagination.
# For more information on collections see the Jekyll documentation.
collections:
  pages:
    output: true
    permalink: /:title
  posts:
    permalink: /nieuws/:title/
  projects:
    output: true
    permalink: /projecten/:title/
  team:
    output: false
