timezone: Amsterdam/Europe
# Jekyll collections for pagination.
# For more information on collections see the Jekyll documentation.
collections:
  pages:
    output: true
    permalink: /:title
  posts:
    permalink: /nieuws/:title/
  projects:
    output: true
    permalink: /projecten/:title/
